language: ruby
rvm:
- 2.0.0
before_script:
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: TFo6TD+dFgU6ZEol/rcsO89BUUtijj8Q1MRtoTi+tpNlBy1LKnfxHxcgfsgAOuA34NH83sE6LDsTHerA6mxvR272neCgqAEvU/gWR+tdKaddiViRg0YRV5CGk2KURLP3FfzvAhDT0L+T71ny5ZcEOsgdYR2ZjKLE7n5p/xv+za0=
  app: the-tangent
notifications:
  flowdock:
    secure: gCSdqPaNmSCCJ7foV0xQRASvvi1CB0+NUj0yqswrKm4T9v1z2WaKI1FCqp7+ltuJP5FXZZPnEIQObfMPfq7iy0EMbk7LAOROrdf67kv95rxr8nP7+gHo2LNyJKP0yxSovoJuUOWAxh/+07E35tQ2ghwPsBIyrumBmxlpRDEZsQc=
